<a href="https://colab.research.google.com/github/necrodancer/Today-I-learned/blob/master/torch/Pytorch60min_whatispytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

\[Notice\] This notebook is reproduction of PyTorch tutorial.
https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

# PYTORCH가 무엇인가요?

파이썬 기반의 과학 연산 패키지. 다음 대상에 유용 : 
1. Numpy 대체하면서 GPU 연산이 필요한 경우
2. 딥러닝 연구 플랫폼


## 시작하기
### Tensors
ndarray와 유사. GPU 연산 가속도 가능

In [0]:
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 5x3 행렬
x = torch.empty(5, 3)
print(x)

tensor([[4.0771e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [3]:
# 무작위로 초기화된 행렬
x = torch.rand(5, 3)
print(x)

tensor([[0.4004, 0.2467, 0.8826],
        [0.9297, 0.8515, 0.6938],
        [0.7734, 0.3071, 0.5797],
        [0.9046, 0.7558, 0.1652],
        [0.6779, 0.8665, 0.7041]])


In [4]:
# dtype이 long이고 0으로 채워진 행렬
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 응용 1 : dtype이 float32이고 0으로 채워진 행렬
x = torch.zeros(5, 3, dtype=torch.float32)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# 데이터로부터 직접 tensor 생성
x =  torch.tensor([5.5, 3])  # 데이터 = 리스트
print(x)

tensor([5.5000, 3.0000])


In [7]:
# 존재하는 tensor를 바탕으로 tensor 생성. 속성(dtype)은 입력 텐서의 것을 따라감.
x = x.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받는다.
print(x)

x = torch.randn_like(x, dtype=torch.float)  # dtype을 오버라이드한다.
print(x) # 결과는 동일한 크기를 가진다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1808,  1.1415, -1.0520],
        [ 0.2411, -1.1834,  0.1714],
        [-0.1285,  1.9084, -1.5900],
        [ 1.5189,  0.6208, -0.3279],
        [-0.5762, -0.2538, -0.8787]])


In [8]:
# 행렬의 크기
print(x.size()) # torch.Size는 튜플과 동일, 모든 튜플 연산을 지원함.

torch.Size([5, 3])


### 연산

In [9]:
# 덧셈: 문법 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7056,  1.4741, -0.4811],
        [ 0.2457, -0.2482,  0.3451],
        [ 0.2779,  2.0381, -0.9655],
        [ 1.7198,  1.4399, -0.1659],
        [-0.0844,  0.2388, -0.6407]])


In [10]:
# 덧셈: 문법2
print(torch.add(x, y))

tensor([[ 1.7056,  1.4741, -0.4811],
        [ 0.2457, -0.2482,  0.3451],
        [ 0.2779,  2.0381, -0.9655],
        [ 1.7198,  1.4399, -0.1659],
        [-0.0844,  0.2388, -0.6407]])


In [11]:
# 덧셈: 결과 tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7056,  1.4741, -0.4811],
        [ 0.2457, -0.2482,  0.3451],
        [ 0.2779,  2.0381, -0.9655],
        [ 1.7198,  1.4399, -0.1659],
        [-0.0844,  0.2388, -0.6407]])


In [12]:
# 덧셈: 바꿔치기(In-place) 방식, y에 x 더하기.
# 참고: 바꿔치기 방식으로 tensor 변경 연산은 `_`를 접미사로 가짐
# (ex. x.copy_(y), x.t_()는 x를 변경함)
y.add_(x)
print(y)

tensor([[ 1.7056,  1.4741, -0.4811],
        [ 0.2457, -0.2482,  0.3451],
        [ 0.2779,  2.0381, -0.9655],
        [ 1.7198,  1.4399, -0.1659],
        [-0.0844,  0.2388, -0.6407]])


In [13]:
# Numpy 스타일의 인덱싱도 가능
print(x[:, 1])

tensor([ 1.1415, -1.1834,  1.9084,  0.6208, -0.2538])


In [14]:
# 크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면
# torch.view를 사용하자. reshape 같은 기능이다.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# 만약 tensor에 하나의 값만 존재한다면, .item()으로 숫자 값 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item(), type(x.item()))

tensor([0.2472])
0.24724043905735016 <class 'float'>


더 읽을거리:

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은 [여기](https://pytorch.org/docs/stable/torch.html)에 설명되어 있습니다.

100가지이기 때문에 시간 관계 상 스킵.


### NumPy 변환(Bridge)
Torch tesnor를 numpy array로 변환하거나 그 반대로 할 수 있다.

CPU 상의 torch tensor와 numpy array는 저장 공간을 공유한다. 

하나를 변경하면 다른 하나도 변경한다.

In [16]:
# torch tensor -> numpy array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
# numpy array 값 변화를 확인해보기
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
# numpy -> torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제와한 CPU 상의 모든 tensor는 numpy 변환이 가능하다. 역변환도 가능하다.

In [20]:
# CUDA Tensor : .to 메소드를 이용해 어떤 장치로든 tensor를 옮길 수 있다.
if torch.cuda.is_available():
  device = torch.device("cuda")  # CUDA 장치 객체로
  y =  torch.ones_like(x, device=device)  # GPU 상에 직접 tensor를 생성하거나
  x = x.to(device)  # .to("cuda")를 사용하면 된다.
  z = x + y
  print(z)
  print(z.to("cpu", torch.double)) # .to는 dytpe도 함께 변경 가능
  

tensor([1.2472], device='cuda:0')
tensor([1.2472], dtype=torch.float64)
