# 3분 딥러닝 3장 실습

# 20171130 목
p.35~38

작성된 소스 코드의 출처 : https://github.com/golbin/TensorFlow-Tutorials

In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello, TensorFlow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


tf.constant의 반환값은 Tensor()라고 해서 자료형과 속성에 대해 설명한다.

In [3]:
3

3

In [4]:
[1., 2., 3.]

[1.0, 2.0, 3.0]

In [5]:
[[1., 2., 3.], [4., 5., 6.]]

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

텐서는 텐서플로에서 수학식 계산을 위한 가장 기본적인 자료형.


랭크 = '\['의 갯수, 즉 차원 수. 
(예) 3 : 랭크 0, [3]: 랭크 1, [[3]]: 랭크 2, [[[3]]]: 랭크 3

랭크 0부터 순서대로, 스칼라, 벡터, 행렬, ... n차원 텐서라고 부른다.

셰이프는 랭크 별 원소 개수.
(예) 3 : 랭크 0 셰이프 \[\], \[3\] : 랭크 1 셰이프 \[1\], [[[1., 2., 3.]],[[1., 2., 3.]]] : 랭크 3 셰이프 [2, 1, 3]

In [6]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


텐서플로우 프로그램 구조 : 1. 그래프 생성(동그라미, tf.constant, tf.add, ...) 2. 그래프 실행(Session run). 이런 실행 방식을 '지연 실행' 또는 'Lazy Evaluation'이라고 부른다.

In [8]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a, b, c]))

sess.close()

Hello, TensorFlow!
[10, 32, 42]


그래프의 실행은 세션 안에서 이루어져야 한다. 아래는 전체 코드

In [9]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
print(hello)

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

sess = tf.Session()
print(sess.run(hello))
print(sess.run([a, b, c]))

sess.close()

Tensor("Const_3:0", shape=(), dtype=string)
Tensor("Add_1:0", shape=(), dtype=int32)
Hello, TensorFlow!
[10, 32, 42]


정리 : 텐서플로우는 그래프 기반 머신러닝 라이브러리이다. 프로그램 실행은 그래프 생성, 그래프 실행 순으로 진행된다. 랭크는 \[의 개수이며 차원 수를 의미한다. 랭크 0부터 스칼라, 벡터, 행렬, ... n차원 텐서라고 부른다. 셰이프는 각 랭크 별 원소 수를 뜻한다. [제일 큰 랭크의 원소수, 그 다음 랭크의 원소 수, ... ]로 적힌다.

# 20171206 수
<br>
p.38~
<br>
플레이스홀더와 변수
플레이스홀더 : 그래프에 입력 값을 담을 그릇(parameter)을 담당.
변수(variable) : 학습 함수들이 학습 결과를 갱신하기 위해 사용하는 변수(가중치).

In [4]:
# None : 크기가 정해져 있지 않다.
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [5]:
x_data = [[1,2,3],[1,2,3]]

In [6]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

tf.random_normal은 정규 분포를 따르는 무작위 값으로 초기화한다는 뜻.

In [7]:
expr = tf.matmul(X, W) + b

[2,3]행렬 = 행이 2, 열이 3
<br>
(예) [[1,2,3],[1,2,3]] : [2, 3] 행렬

In [8]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [1, 2, 3]]
=== W ===
[[ 0.51939726  0.68138808]
 [ 1.71464252 -0.77968597]
 [ 0.19617501 -0.22691396]]
=== b ===
[[ 0.66313279]
 [ 0.87909079]]
=== expr ===
[[ 5.20034027 -0.89559305]
 [ 5.41629839 -0.67963505]]


placeholder가 session에서 돌아가려면 feed_dict를 통해 입력 데이터를 별도로 넣어야 에러가 나지 않는다.
<br>
애초에 placeholder는 그릇이니까 내용물을 feed_dict로 담는 건 자연스러운 일이다.