# TF.ARGMAX 실습

2018년 2월 9일 금요일

In [3]:
import tensorflow as tf

a = tf.Variable([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])

In [4]:
print(a)

<tf.Variable 'Variable_2:0' shape=(4, 4) dtype=int32_ref>


In [5]:
b = tf.Variable([[[[[1,1]]]]])
print(b)

<tf.Variable 'Variable_3:0' shape=(1, 1, 1, 1, 2) dtype=int32_ref>


shape는 가장 바깥의 테두리 개수부터 세아린다.

In [9]:
c = tf.Variable([1,2],[3,4])
print(c)

<tf.Variable 'Variable_6:0' shape=(2,) dtype=int32_ref>


In [12]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(c))
sess.close()

[1 2]


저런 식으로 선언하면 , 뒤의 리스트는 저장이 되지 않는다.

In [14]:
d = tf.Variable([[[0,1,2],[1,2,0],[2,0,1]],
                 [[2,1,0],[1,0,2],[0,2,1]],
                 [[1,0,2],[2,1,0],[2,0,1]]])
print(d)
e = tf.argmax(d,axis=0)
f = tf.argmax(d,axis=1)
g = tf.argmax(d,axis=2)

<tf.Variable 'Variable_8:0' shape=(3, 3, 3) dtype=int32_ref>


In [17]:
sess =tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(e))
print(sess.run(f))
print(sess.run(g))
sess.close()

[[1 0 0]
 [2 0 1]
 [0 1 0]]
[[2 1 0]
 [0 2 1]
 [1 1 0]]
[[2 1 0]
 [0 2 1]
 [2 0 0]]


나의 예측:<br>
e : [[1,0,0],[2,0,1],[0,1,0]]<br>
f : [[2,1,0],[0,2,1],[1,1,0]]<br>
g : 잘 모르겠다.<br>

In [18]:
h = tf.Variable([[[4,5,6],[7,0,4]],
                 [[8,2,3],[6,9,5]]])
i = tf.argmax(h,0)
j = tf.argmax(h,1)
k = tf.argmax(h,2)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(i))
print(sess.run(j))
print(sess.run(k))

[[1 0 0]
 [0 1 1]]
[[1 0 0]
 [0 1 1]]
[[2 0]
 [0 1]]


##### What I realized
axis = 0 일때는 **가장 큰(바깥) 테두리끼리** 비교하고,<br>
axis = 1 일때는 **그 다음 큰 테두리들 안에서** 비교하고,<br>
axis = max 일때는 **가장 작은 테두리 안(벡터)에서** 비교하는군!<br>
<br>
\+ shape를 표기할때는 (가장 큰 테두리, 그 다음 테두리, ... , 가장 테두리 안의 원소 수)와 같