# Indexing nonzero sub-arrays in numpy

Purpose
---
Let there is array like this :

In [3]:
import numpy as np
a = np.array([
    [0,0,0,0],
    [0,0,0,1],
    [0,0,0,0],
    [0,0,1,0]
])
print("Array a:")
print(a)

Array a:
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 1 0]]


There are some non-zero rows in the array `a`, i.e row number 1 and 3. <br>
What should we do If we want to know indices of non-zero rows <br>
not the specific indices of non-zero elements?

numpy.nonzero()
---
numpy.nonzero() returns every indices of each axis of array.

In [5]:
nz_idx = np.nonzero(a)
print(nz_idx)

(array([1, 3]), array([3, 2]))


As you can see, the first `array([1, 3])` indicates what we want to know; rows of non-zero. <br>
And the other `array([3, 2])` shows the columns of non-zero.<br>
But, if we have the multiple non-zeros in a row as below array `b`, what will happen?

In [6]:
b = np.array([
    [0,0,0,0],
    [0,0,1,1],
    [0,0,0,0],
    [0,1,1,0]
])
print("Array b:")
print(b)

Array b:
[[0 0 0 0]
 [0 0 1 1]
 [0 0 0 0]
 [0 1 1 0]]


In [7]:
nz_idx = np.nonzero(b)
print(nz_idx)

(array([1, 1, 3, 3]), array([2, 3, 1, 2]))


It returns multiple same row indices. <br>
If we want to unique indices of row of non-zeros, <br>
just apply `set`.

In [9]:
nz_idx = np.nonzero(b)
nz_rows = set(nz_idx[0])
print(nz_rows)

set([1, 3])


If it is not sorted, you can add `sorted` method.
It will return not `set` type but `list` type.

In [10]:
nz_idx = np.nonzero(b)
nz_rows = sorted(set(nz_idx[0]))
print(nz_rows)

[1, 3]


Application
---
If you want to index non-zero segmentation slices among a bunch of zero slices in CT-image,
This code will be help you.

In [ ]:
nz_idx = np.nonzero(b)
nz_rows = sorted(set(nz_idx[0]))
print(nz_rows)

Or, the reference code from the official document of numpy is also useful.

In [14]:
c = np.array([[1,2],[0,1]])
d = c > 1
print(d.nonzero())

(array([0]), array([1]))


# References
\[1\] [(파이썬) numpy.nonzero](http://codepractice.tistory.com/90)<br>
\[2\] [numpy.nonzero](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nonzero.html)