# Add a new column or row in array(Numpy)

## Method 1 : Indexing Manually

In [17]:
import numpy as np

# Create two arrays to concatenate.
a = np.eye(3) # base 
b = np.ones((3,1)) # new column to add

# Display
print("a : ")
print(a)
print(a.shape)
print("b : ")
print(b)
print(b.shape)

a : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
b : 
[[1.]
 [1.]
 [1.]]
(3, 1)


In [25]:
# Add a new column in numpy
concat = np.zeros((len(a),len(a)+1)) # create background array to add both arrays.
concat[:,[0,1,2]] = a # insert a
concat[:,[-1]] = b # insert b

# Display
print(concat)
print(concat.shape)

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]
(3, 4)


## Method 2 : Using np.c_[arr1, arr2], np.r_[arr1, arr2]

In [34]:
print(np.c_[a, b]) # add a new column

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]


In [35]:
print(np.r_[a, np.transpose(b)]) # add a new row

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]]


## Method 3 : Using np.append

In [29]:
print(np.append(a,b,axis=1))

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]


In [31]:
print(np.append(a,np.transpose(b),axis=0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]]


## Method 4 : Using np.hstack, np.vstack

In [32]:
print(np.hstack([a, b]))

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]]


In [33]:
print(np.vstack([a, np.transpose(b)]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 1.]]


# References
[Numpy array Korean](https://datascienceschool.net/view-notebook/17608f897087478bbeac096438c716f6/)
<br> [Numpy add an extra column (stack overflow)](https://stackoverflow.com/questions/8486294/how-to-add-an-extra-column-to-an-numpy-array)